version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL
      - STAGING
      - DHPARAM_SIZE
      - RSA_KEY_SIZE
      - ELLIPTIC_CURVE
      - USE_ECDSA
      - RENEWAL_INTERVAL
      - DEBUG
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d

volumes:
  nginx_secrets:
